### ISSUE TITLE
Update wants access to all sites

### ISSUE THREAD

**Issue by zefie** [brian-girko/always-active#19]
I have v0.2.3, and have it limited to only access twitch.tv as this is the site I need it to work on. It has been working great to prevent their onblur bandwidth downgrade system that 9/10 times breaks streams.

But now my flavor of chromium is bugging me to update the extension, and that the addon now requires "Read and change all your data on all websites". If I upgrade can I revert back to twitch only? If not, why does the extension now require access to all sites?

Thanks!

**Comment by brian-girko** [comment]
There is no change in the permission set of this extension. I have no idea why you got this permission warning right now. 

Since this is an aggressive extension, it is recommended to limit the extension access to a limited number of hostnames by following FAQ5;

https://add0n.com/always-active.html

**Comment by zefie** [comment]
Okay, thanks! It could just be something silly with Opera. I am guessing I will just have to reconfigure it after it gets the "all" permission, like when I initially installed it. Thanks again for the great extension.
